name: Simulate Blink on Wokwi

on:
  push:
    paths:
      - '**/*.ino'
      - 'wokwi.toml'

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download and install wokwi-cli
        run: |
          wget -q -O /usr/local/bin/wokwi-cli https://github.com/wokwi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
          chmod +x /usr/local/bin/wokwi-cli

      - name: Run simulation using wokwi.toml
        run: wokwi-cli --timeout 30000
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}

